#!/usr/bin/env python

from Bio.Seq import Seq
from Bio.Alphabet import generic_dna, generic_protein
import fileinput

i = 0
for line in fileinput.input():
    if i % 4 == 1:
        print str(Seq(line[:-1], generic_dna).reverse_complement())
    else:
        print line[:-1]
    i += 1
